// Edit-mode tuning: the admin builds two weeks by hand (editor.html).
//
//   node edit.js gen [--round 1] [--n 24] [--seed …] [--weights fitted.json]
//       (--weights pre-fills the editor with the optimizer's plan under them)
//       → edit-r<round>.js  (window.EDIT_SCENARIOS[round] = [...])
//   node edit.js ingest edits.json [--out pairs-edit.json]
//       → pairwise observations for fit.js: "admin's plan ≥ alternative"
//   node edit.js check edits.json [fitted-weights.json]
//       → how many cells the optimizer (current, and fitted if given)
//         gets different from the admin's hand-built plan
//
// Needs puppeteer-core on NODE_PATH (see README).

const path = require('path');
const fs = require('fs');
const { openApp } = require('./browser');

const cmd = process.argv[2];
const arg = (k, d) => { const i = process.argv.indexOf('--' + k); return i > 0 ? process.argv[i + 1] : d; };
const pos = process.argv.slice(3).filter((a, i, all) => !a.startsWith('--') && !(all[i - 1] || '').startsWith('--'));

// Two-week-friendly change kinds (no two-week PTO: nothing left to edit).
const KINDS = ['pto1', 'ptoFriMon', 'ptoThuFri', 'lockWfh', 'ptoWeek', 'ptoTwo', 'lockHuntley',
    'ptoFri', 'ptoRemove', 'pto1', 'lockWeek', 'ptoFriMon', 'ptoHoliday', 'lockWfh'];

async function gen() {
    const round = parseInt(arg('round', '1'), 10);
    const n = parseInt(arg('n', '24'), 10);
    const seed = parseInt(arg('seed', String(50000 + round * 1000)), 10);
    const wfile = arg('weights', null);
    const startW = wfile ? JSON.parse(fs.readFileSync(wfile, 'utf8')).weights : null;
    const { page, close } = await openApp();
    const out = [];
    try {
        for (let i = 0; i < n; i++) {
            const spec = { id: 'e' + round + 's' + i, seed: seed + i * 7919, kind: KINDS[i % KINDS.length], bg: i % 3 !== 0, v: 2 };
            if (startW) spec.startW = startW;
            const s = await page.evaluate(sp => tuneEditSituation(sp), spec);
            console.error(`${spec.id} ${spec.kind}${spec.bg ? '+bg' : ''}: ${s.desc}`);
            out.push(s);
        }
    } finally { await close(); }
    const file = path.join(__dirname, 'edit-r' + round + '.js');
    fs.writeFileSync(file, '// Generated by edit.js gen — round ' + round + '\nwindow.EDIT_SCENARIOS = window.EDIT_SCENARIOS || {};\nwindow.EDIT_SCENARIOS[' + round + '] = '
        + JSON.stringify(out) + ';\n');
    console.error('wrote ' + out.length + ' scenarios to ' + file);
}

function loadEdits(files) {
    const all = [];
    files.forEach(f => JSON.parse(fs.readFileSync(f, 'utf8')).forEach(e => all.push(e)));
    return all.filter(e => e.done);
}

async function ingest() {
    const edits = loadEdits(pos);
    const outFile = arg('out', path.join(__dirname, 'pairs-edit.json'));
    const { page, close } = await openApp();
    const pairs = [];
    try {
        for (const e of edits) {
            const r = await page.evaluate((sp, m) => tuneEvalEdit(sp, m), e.spec, e.plan);
            if (r.error) { console.error(`${e.id}: skipped — ${r.error}`); continue; }
            const nb = r.alts.filter(a => a.kind === 'neighbor').length;
            r.alts.forEach((a, ai) => {
                // Whole-plan alternatives are strong evidence; the many
                // one-day tweaks share a fixed total weight per scenario.
                const v = a.kind === 'neighbor' ? 8 / Math.max(1, nb) : 2;
                pairs.push({ qid: e.id + ':' + ai + ':' + a.label, group: e.id, kind: e.kind, desc: e.desc, v, note: e.note || '',
                    A: { labels: ['admin'], f: r.user }, B: { labels: [a.label], f: a.f } });
            });
            console.error(`${e.id}: ${r.alts.length} alternatives (${nb} one-day)`);
        }
    } finally { await close(); }
    fs.writeFileSync(outFile, JSON.stringify(pairs));
    console.error('wrote ' + pairs.length + ' observations to ' + outFile);
}

async function check() {
    const edits = loadEdits(pos.filter(f => !/fitted/.test(f)));
    const wf = pos.find(f => /fitted/.test(f));
    const fitted = wf ? JSON.parse(fs.readFileSync(wf, 'utf8')).weights : null;
    const { page, close } = await openApp();
    try {
        let tot = { cells: 0, cur: 0, fit: 0, curExact: 0, fitExact: 0 };
        for (const e of edits) {
            const r = await page.evaluate(async (sp, plan, fw) => {
                const diff = m => Object.keys(plan).reduce((n, k) => n + Object.keys(plan[k]).filter(p => m[k] && m[k][p] !== plan[k][p]).length, 0);
                _tSetW({});
                const { from, pins, changers } = await _tSetup(sp);
                const W = _tEditWindow(from);
                let prob = _tEditProblem(W.win, pins, changers);
                const cur = diff(_tPlanMap(prob, _tSolve(prob)));
                let fit = null;
                if (fw) {
                    _tSetW(tuneWeightsFromFit(fw));
                    prob = _tEditProblem(W.win, pins, changers);
                    fit = diff(_tPlanMap(prob, _tSolve(prob)));
                    _tSetW({});
                }
                const cells = Object.keys(plan).reduce((n, k) => n + Object.keys(plan[k]).length, 0);
                return { cur, fit, cells };
            }, e.spec, e.plan, fitted);
            tot.cells += r.cells; tot.cur += r.cur; if (!r.cur) tot.curExact++;
            if (r.fit !== null) { tot.fit += r.fit; if (!r.fit) tot.fitExact++; }
            console.log(`${e.id.padEnd(8)} ${e.kind.padEnd(12)} cells differing from yours: current ${r.cur}` + (r.fit !== null ? `, fitted ${r.fit}` : '') + `  (of ${r.cells})`);
        }
        console.log(`\nTotal: current weights differ on ${tot.cur}/${tot.cells} cells, exact match ${tot.curExact}/${edits.length} scenarios`);
        if (fitted) console.log(`       fitted weights differ on ${tot.fit}/${tot.cells} cells, exact match ${tot.fitExact}/${edits.length} scenarios`);
    } finally { await close(); }
}

({ gen, ingest, check })[cmd]().catch(e => { console.error(e); process.exit(1); });
